name: postgres

on:
  push:
    branches:
      - master
    paths:
      - 'postgres/**'
      - '!**.md'
      - '!postgres/LICENSE'
      - '.github/workflows/postgres.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build all
      run: |
        docker run \
              --rm \
              --privileged \
              -v ~/.docker:/root/.docker \
              -v $(pwd)/hassio-addon-repository/postgres:/data homeassistant/amd64-builder \
              --all \
              --target /data
