name: postgres

on:
  push:
    branches:
      - master
    paths:
      - 'postgres/**'
      - '!**.md'
      - '!postgres/LICENSE'
      - '.github/workflows/postgres.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to docker hub
      run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build all
      run: |
        sudo docker run \
              --rm \
              --privileged \
              -v /run/docker.sock:/run/docker.sock:rw \
              -v ~/.docker:/root/.docker \
              -v $(pwd)/postgres:/data homeassistant/amd64-builder \
              --all \
              --target /data
