name: teslamate

on:
  push:
    branches:
      - master
    paths:
      - 'teslamate/**'
      - '!**.md'
      - '.github/workflows/teslamate.yml'

jobs:
  build:
    env:
      TESLAMATE_TAG: 1.19.1

    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, armhf, armv7, aarch64, i386]
      fail-fast: true

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Login to docker hub
      run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Create docker image
      run: |
        sudo docker run \
              --rm \
              --privileged \
              -v /run/docker.sock:/run/docker.sock:rw \
              -v ~/.docker:/root/.docker \
              -v $(pwd)/$GITHUB_WORKFLOW:/data homeassistant/amd64-builder \
              --${{ matrix.arch }} \
              --target /data
